# .github/workflows/snake.yml
name: Update Snake Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'   # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sdn9300
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4691f9,#1165e3

      - name: Push changes to main
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
